# Generated by Django 5.0.6 on 2024-05-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0002_rename_pessoa_cliente_rename_pessoa_venda_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Venda.cliente')),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=200)),
            ],
            bases=('Venda.cliente',),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='ClienteFisico',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Venda.cliente')),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
            ],
            bases=('Venda.cliente',),
        ),
    ]
