# Generated by Django 5.0.6 on 2024-05-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0004_alter_venda_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientejuridico',
            name='cliente_ptr',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.DeleteModel(
            name='ClienteFisico',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ClienteJuridico',
        ),
    ]
