# Generated by Django 5.0.6 on 2024-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0007_rename_image_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(default=0, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
