# Generated by Django 5.0.6 on 2024-06-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0008_remove_produto_imagem_produto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
