# Generated by Django 5.0.6 on 2024-06-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venda', '0009_alter_produto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=0, upload_to='produto_imagens'),
            preserve_default=False,
        ),
    ]
